baseURL = "https://komisan19.dev/"
title = "komisan19 dev"
theme = "anatole"
languageCode = "ja"
defaultContentLanguage = "ja"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "G-J309CM6HYZ"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "komisan19 dev"
author = "komsian19"
copyright = "2021"
description = "I'm Web Engineer. I love Goüòç"
profilePicture = "images/gozira.webp"
keywords = "blog, developer, Go"
favicon = "favicons/"
#displayMode = "dark"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = []
images = ["images/favicon.webp"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
# indexDateFormat = "Mon, Jan 2, 2006"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/komisan19/"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/komisan19"

## Menu items

[Languages]
  [Languages.ja]
    title = "komisan19 dev"
    weight = 100
    LanguageName = "JP"
    contentDir = "content/ja"

  [[Languages.ja.menu.main]]
    name   = "home"
    url    = "/"
    identifier = "home"
    weight = 100
  
  [[Languages.ja.menu.main]]
    name = "posts"
    weight = 200
    identifier = "posts"
    url = "/post/"
  
  [[Languages.ja.menu.main]]
    name = "Project"
    weight = 300
    identifier = "projects"
    url = "/projects"

  [Languages.en]
    title = "komisan19 dev"
    weight = 100
    LanguageName = "EN"
    contentDir = "content/en"

  [[Languages.en.menu.main]]
    name   = "home"
    url    = "/en"
    identifier = "home"
    weight = 100
  
  [[Languages.en.menu.main]]
    name = "posts"
    weight = 200
    identifier = "posts"
    url = "/en/post/"
  
  [[Languages.en.menu.main]]
    name = "Project"
    weight = 300
    identifier = "projects"
    url = "/en/projects"
